spring.application.name=?

spring.servlet.multipart.max-file-size=?MB
spring.servlet.multipart.max-request-size=?MB

GOOGLE_API_KEY=YOUR_API_KEY

spring.datasource.url=YOUR_URl
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD